### ISSUE TITLE
Rolio is broken

### ISSUE THREAD

**Issue by rjwright** [web-animations/web-animations-demos#62]

**Comment by robcolburn** [comment]
There seems to be a JS bug whereby you are attempting to get the "next length" which doesn't exist yet, when the "time fraction" is 1.

![](https://cloud.githubusercontent.com/assets/245860/8914286/345d3f8e-3453-11e5-9cc9-dff8858545f7.png)

![](https://cloud.githubusercontent.com/assets/245860/8914288/37be50c8-3453-11e5-8619-38476cef4fc9.png)

**Comment by appsforartists** [comment]
I'm seeing `Uncaught ReferenceError: SVGPathSegList is not defined`.  Perhaps it should be removed from the demo site sidebar until it's fixed.

**Comment by samthor** [comment]
We've disabled this and it's unlikely to return. Closing issue.
