### ISSUE TITLE
Inline breakout.js

### ISSUE THREAD

**Issue by appsforartists** [web-animations/web-animations-demos#73]
http://web-animations.github.io/web-animations-demos/#breakout

If you click the Code button, all it shows is an HTML scaffold that marshals out to breakout.js.  To maintain consistency with the other demos, the script should be inlined.

A similar issue exists for the touch demo in #72

**Comment by samthor** [comment]
I've resolved this but we've also currently disabled the demo as it uses the very old, legacy polyfill.
