### ISSUE TITLE
Code button broken

### ISSUE THREAD

**Issue by samuelli** [web-animations/web-animations-demos#77]
Repro steps

1. Go to https://web-animations.github.io/web-animations-demos/
2. Go to a demo and tap 'code'.

Code doesn't show, insecure mixed content.

**Comment by alancutter** [comment]
It appears that GAE redirects HTTPS requests for directories to the HTTP equivalent.

**Comment by alancutter** [comment]
Relevant bug: https://github.com/isaacs/github/issues/289
Relevant new feature: https://github.com/blog/2186-https-for-github-pages
Relevant instructions: https://help.github.com/articles/securing-your-github-pages-site-with-https/

I ticked the box in settings. Problem hasn't been fixed but maybe it takes a while for the setting to take effect.

**Comment by alancutter** [comment]
The workaround is to simply add a '/' to the end of directory paths, I may as well just do that anyway.
