### ISSUE TITLE
Ripple demo code

### ISSUE THREAD

**Issue by caub** [web-animations/web-animations-demos#88]
I looked at the code of https://web-animations.github.io/web-animations-demos/#ripple/, it was terrible so I made: https://jsfiddle.net/0w9oge6g/1/

**Comment by samthor** [comment]
Thanks, but the demo works fine so I'll leave it for now. Please submit a PR if you feel differently (note that it should be ES5 features only).

**Comment by caub** [comment]
Yes it works fine right, was talking about the code, it's fine

for es5, just 3 arrows to change to function
